//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vikar_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VikarEntity : DbContext
    {
        public VikarEntity()
            : base("name=VikarEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kommentar> Kommentars { get; set; }
        public virtual DbSet<Køn> Køn { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Område> Område { get; set; }
        public virtual DbSet<Profil> Profils { get; set; }
    }
}
