//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vikar_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Område
    {
        public int Område_Id { get; set; }
        public string Område1 { get; set; }
    }
}
